### ISSUE TITLE
Installing Viper4Android module will cause browsers to not render anything

### ISSUE THREAD

**Issue by SapitoSucio** [AndroidAudioMods/ViPER4Android#107]
I just confirmed it.

Edge, Edge Beta, Chrome doesn't work

Firefox focus does work 

My device is Moto Edge 30, Android 15, KSU

Disabling the module makes it work again

**Comment by drwpls** [comment]
Same issue
1+ ACE 3V, Android 15, KSU

**Comment by SapitoSucio** [comment]
> Same issue 1+ ACE 3V, Android 15, KSU

I further tested and it's the same output when I tried other V4A modules, this problem is not limited to this one module only

**Comment by drwpls** [comment]
I put this and hope it help
`
--------- beginning of crash
07-09 18:55:46.765  6350  6350 E AndroidRuntime: FATAL EXCEPTION: main
07-09 18:55:46.765  6350  6350 E AndroidRuntime: Process: com.aam.viper4android, PID: 6350
07-09 18:55:46.765  6350  6350 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at android.util.SparseArray.keyAt(SparseArray.java:316)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at o1.t.a(SourceFile:149)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at v1.f0.m(SourceFile:144)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at o5.a.i(SourceFile:1)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at d6.c0.run(SourceFile:1)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at d6.k0.G(SourceFile:24)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at d6.h.s(SourceFile:95)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at d6.h.k(SourceFile:1)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at f6.d.a(SourceFile:1)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at f6.b.u(SourceFile:37)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at f6.b.d(SourceFile:57)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at f6.b.b(SourceFile:107)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at com.google.android.gms.internal.measurement.m3.z(SourceFile:49)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at com.aam.viper4android.service.ViPERService.onStartCommand(Unknown Source:82)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5082)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2432)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
07-09 18:55:46.765  6350  6350 E AndroidRuntime: 	Suppressed: i6.g: [b1{Cancelling}@572a7b5, Dispatchers.Main.immediate]
07-09 19:15:45.013 13902 13902 E AndroidRuntime: FATAL EXCEPTION: main
07-09 19:15:45.013 13902 13902 E AndroidRuntime: Process: com.aam.viper4android, PID: 13902
07-09 19:15:45.013 13902 13902 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at android.util.SparseArray.keyAt(SparseArray.java:316)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at o1.t.a(SourceFile:149)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at v1.f0.m(SourceFile:144)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at o5.a.i(SourceFile:1)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at d6.c0.run(SourceFile:1)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at d6.k0.G(SourceFile:24)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at d6.h.s(SourceFile:95)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at d6.h.k(SourceFile:1)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at f6.d.a(SourceFile:1)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at f6.b.u(SourceFile:37)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at f6.b.d(SourceFile:57)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at f6.b.b(SourceFile:107)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at com.google.android.gms.internal.measurement.m3.z(SourceFile:49)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at com.aam.viper4android.service.ViPERService.onStartCommand(Unknown Source:82)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5082)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2432)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
07-09 19:15:45.013 13902 13902 E AndroidRuntime: 	Suppressed: i6.g: [b1{Cancelling}@138dc15, Dispatchers.Main.immediate]
07-14 13:56:02.008 25968 25968 E AndroidRuntime: FATAL EXCEPTION: main
07-14 13:56:02.008 25968 25968 E AndroidRuntime: Process: com.google.android.gms.ui, PID: 25968
07-14 13:56:02.008 25968 25968 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 946332 bytes
07-14 13:56:02.008 25968 25968 E AndroidRuntime: Bundle stats:
07-14 13:56:02.008 25968 25968 E AndroidRuntime:   _chimera_module_state [size=945872]
07-14 13:56:02.008 25968 25968 E AndroidRuntime:     androidx.lifecycle.BundlableSavedStateRegistry.key [size=944236]
07-14 13:56:02.008 25968 25968 E AndroidRuntime:       android:support:activity-result [size=1264]
07-14 13:56:02.008 25968 25968 E AndroidRuntime:       android:support:fragments [size=942596]
07-14 13:56:02.008 25968 25968 E AndroidRuntime:         fragment_9acc7c44-60d5-4c8d-aafa-6555d342ad72 [size=942088]
07-14 13:56:02.008 25968 25968 E AndroidRuntime:           viewState [size=7676]
07-14 13:56:02.008 25968 25968 E AndroidRuntime:           savedInstanceState [size=933456]
07-14 13:56:02.008 25968 25968 E AndroidRuntime:             is_pkpasses [size=933344]
07-14 13:56:02.008 25968 25968 E AndroidRuntime: PersistableBundle stats:
07-14 13:56:02.008 25968 25968 E AndroidRuntime:   [null]
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:146)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 946332 bytes
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:586)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1527)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.app.ActivityClient.activityStopped(ActivityClient.java:101)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
07-14 13:56:02.008 25968 25968 E AndroidRuntime: 	... 8 more
07-17 20:48:44.015  5801  5801 E AndroidRuntime: FATAL EXCEPTION: main
07-17 20:48:44.015  5801  5801 E AndroidRuntime: Process: com.aam.viper4android, PID: 5801
07-17 20:48:44.015  5801  5801 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at android.util.SparseArray.keyAt(SparseArray.java:316)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at o1.t.a(SourceFile:149)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at v1.f0.m(SourceFile:144)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at o5.a.i(SourceFile:1)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at d6.c0.run(SourceFile:1)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at d6.k0.G(SourceFile:24)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at d6.h.s(SourceFile:95)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at d6.h.k(SourceFile:1)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at f6.d.a(SourceFile:1)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at f6.b.u(SourceFile:37)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at f6.b.d(SourceFile:57)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at f6.b.b(SourceFile:107)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at com.google.android.gms.internal.measurement.m3.z(SourceFile:49)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at com.aam.viper4android.service.ViPERService.onStartCommand(Unknown Source:82)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5082)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2432)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
07-17 20:48:44.015  5801  5801 E AndroidRuntime: 	Suppressed: i6.g: [b1{Cancelling}@d6ffa17, Dispatchers.Main.immediate]
--------- beginning of system
`
