### ISSUE TITLE
Force close android 14

### ISSUE THREAD

**Issue by bombadier** [AndroidAudioMods/ViPER4Android#71]
Both updated app versions are force closing on android 14 
0.6.0 and 0.6.1

FATAL EXCEPTION: main
Process: com.aam.viper4android, PID: 15706
java.lang.RuntimeException: Unable to resume activity {com.aam.viper4android/com.aam.viper4android.MainActivity}: java.lang.SecurityException: com.aam.viper4android: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4982)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5015)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2448)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.SecurityException: com.aam.viper4android: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at r1.o.Y(SourceFile:155)
	at z0.t.x(SourceFile:68)
	at r1.o.x(SourceFile:29)
	at androidx.fragment.app.t0.e(SourceFile:71)
	at androidx.fragment.app.t0.k(SourceFile:152)
	at androidx.fragment.app.o0.A(SourceFile:24)
	at androidx.fragment.app.o0.R(SourceFile:82)
	at androidx.fragment.app.o0.z(SourceFile:32)
	at com.aam.viper4android.MainActivity.e(SourceFile:155)
	at v1.c.G(SourceFile:180)
	at com.aam.viper4android.MainActivity.onResume(SourceFile:58)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:8769)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4972)
	... 13 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13995)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2763)
	at android.os.Binder.execTransactInternal(Binder.java:1332)
	at android.os.Binder.execTransact(Binder.java:1278)

**Comment by Addster09** [comment]
+1

**Comment by Eldreamer13** [comment]
The same problem, S23+ A14. 0.5.0 works fine.

**Comment by bombadier** [comment]
There is an [update on telegram VA4_App_0.6.1_SDK33.apk](https://t.me/ViPER4AndroidFX/284865) that fixes the issue, need to completely uninstall version 0.5.0 to install though
I have switched to using the [material one](https://github.com/WSTxda/ViperFX-RE-Releases/releases/tag/5.6.2) as I think it looks better, uses the same magisk module

**Comment by bombadier** [comment]
Fixed in this [release](https://github.com/AndroidAudioMods/ViPER4Android/releases/tag/v.0.6.2)
